### ISSUE TITLE
Tags added via mflow are not converted to Neptune

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-mlflow#10]
Adding tags via mlflow interface:

```python
with mlflow.start_run():
    mlflow.set_tag('neural network', 'simple')
```

are stored by mlflow in the run directory in a separate `tags` subdirectory.
Since for mlflow `tag` is a `tag_name:tag_value` pair, every mflow `tag` is stored as a file with the `filename=tag_name` which contains `tag_value`. 

As of now `neptune-mlflow` doesn't convert neither `tag_name` nor `tag_value` to Neptune `tag`.

Also, even if I manually add tags to the `meta.yaml`

```yaml
...
start_time: 1553511324389
status: 3
tags: ['fancy_tag', 'smart idea']
...
```

the tags are not added to Neptune (only `Default` is).

I think the tags from the `meta.yaml` should be added automatically.
As for the mlflow run tags I am not sure how to handle them but I would suggest converting both `tag_name` and `tag_value` to tags or combining them to one `tag_name__tag_value` tag.

What do you think @aniezurawski @pitercl ?

**Comment by aniezurawski** [comment]
Tags stored in `tags/` subdir are converted to Neptune properties (since they are key-value pairs).
Currently it seems to be no way to add those other tags from `meta.yaml` file. Also mlflow lib does not provide any method to read them so we do not support them.

**Comment by jakubczakon** [comment]
That is perfect!

**Comment by ShootingStarD** [comment]
When adding tags to neptune, the tags are sent as individual values in the UI : 

![Image](https://github.com/user-attachments/assets/baba8e54-6c9a-469c-8e15-8bd32019b2b0)

Are there plan to make key value pair? And if not , is it possible to, after a set the neptune tags manually
```python
with mlflow.start_run():
   ....
# set the neptune tags manually
```
Knowing that I use the `create_netpune_tracking_uri()` function and thus I do not get a neptune run object on which I can add manual tag

**Comment by SiddhantSadangi** [comment]
Hey @ShootingStarD 👋 

You can pass `tags` to `create_netpune_tracking_uri()`: https://docs.neptune.ai/api/mlflow/
You can also update tags directly from the Neptune UI: https://docs.neptune.ai/usage/adding_tags/#managing-tags-in-the-web-app

Please let me know if this helps
