### ISSUE TITLE
'RunInfo' object has no attribute 'name'

### ISSUE THREAD

**Issue by weng271190436** [neptune-ml/neptune-mlflow#14]
When I run neptune mlflow command, I see this error.

If I change the line 122 of data_loader.py from "run_name = run_info.name or run_info.run_uuid"
to "run_name = run_info.run_uuid", I hit another error at line 90 of data_loader.py saying that a str object doesn't have a property "value"

![image](https://user-images.githubusercontent.com/6925089/60392351-7ab5be80-9ab5-11e9-84fe-fe888cd4011b.png)

**Comment by aniezurawski** [comment]
Hi @weng271190436,

Thanks for your report. This issue was fixed in version 0.1.2 of `neptune-mlflow`. :)
