### ISSUE TITLE
Add warning/error when user points to mlruns dir

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-mlflow#6]
When I run:

```bash
neptune mlflow mlruns
```
Nothing happens and I don't know what is wrong. Maybe we could add a warning or error that gives a message point to the directory above mlruns.

**Comment by aniezurawski** [comment]
What do you think about such warning message: "No `mlruns` directory was found in given path."?
It solves two cases:
1. If user pass `mlruns` directory (there is no `mlruns` inside `mlruns`).
2. If user pass any path not related to mlflow.

**Comment by jakubczakon** [comment]
@aniezurawski sounds perfect. 
Do you think it should be warning or an error?

**Comment by aniezurawski** [comment]
@jakubczakon Definitely an error.

**Comment by aniezurawski** [comment]
Fixed in #8
