### ISSUE TITLE
Non-intuitive experiment name

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-mlflow#9]
Right now experiment name is:

`mlflow/Default/e39cec6d316a4cc88356cf54bde038a2`

while I would expect to have the experiment id in the name, just as in the directory structure of the `mlruns` dir i.e.:

`mlflow/0/e39cec6d316a4cc88356cf54bde038a2`

Is it important to keep the current `Default` name here @aniezurawski ?

**Comment by aniezurawski** [comment]
`Default` is the name of the mlflow experiment. An id is stored in property `mlflow/experiment/id`. I think it's questionable what is more intuitive to be included in the name of Neptune experiment.

**Comment by jakubczakon** [comment]
Sounds great.
